name: Bruna Teles Website
markdown: redcarpet
pygments: true
tag_page_layout: tag_page
tag_page_dir: tag
paginate: 5
paginate_path: "blog/:num"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
